[build]
builder = "nixpacks"

[deploy]
startCommand = "mix ecto.migrate && mix phx.server"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
